@port = 7425

### Get all persons
GET https://localhost:{{port}}/people

### Get a person by ID
GET https://localhost:{{port}}/people/1

### Create a new person
POST https://localhost:{{port}}/people
Content-Type: application/json

{
  "name": "John Doe",
  "age": 100
}

### Update a person by ID
PUT https://localhost:{{port}}/people/1
Content-Type: application/json

{
  "name": "Jane Doe",
  "age": 25
}

### Delete a person by ID
DELETE https://localhost:{{port}}/people/1