// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PersonAPI.Service.Models;

namespace PersonAPI.Service
{

    public interface IPersonOperations
    {
        Task ListPersonsAsync();
        Task<Person> GetPersonAsync(int id);
        Task<Person> CreatePersonAsync(Person person);
        Task<Person> UpdatePersonAsync(int id, Person person);
        Task DeletePersonAsync(int id);

    }
}
